const sampleDetails = [
    {
      name: "Alice Johnson",
      image: "https://cdn.pixabay.com/photo/2023/11/10/02/30/woman-8378634_1280.jpg",
      introduction: "I am currently pursuing my studies in Computer Engineering.",
      course: "Btech",
      status: "Student",
      branch: "Computer Engineering",
      skills: "Java, Python, SQL",
      technology: "web dev",
      projects: "Database Project, Web Development Project",
      college: "University of ABC",
      city: "Boston",
      state: "Massachusetts",
    },
    {
      name: "Bob Smith",
      image: "https://cdn.pixabay.com/photo/2015/07/09/00/29/woman-837156_1280.jpg",
      introduction: "I am a professional web developer with over 5 years of experience.",
      course: "Btech",
      status: "Professional",
      branch: "Web Development",
      skills: "JavaScript, HTML, CSS, React",
      technology: "Android dev",
      projects: "E-commerce website, Portfolio website",
      college: "Tech Institute",
      city: "San Francisco",
      state: "California",
    },
    {
      name: "Eva Martinez",
      image: "https://cdn.pixabay.com/photo/2016/11/29/03/36/woman-1867093_1280.jpg",
      introduction: "I am studying Marketing and have a keen interest in digital marketing strategies.",
      course: "Btech",
      status: "Student",
      branch: "Marketing",
      skills: "Social Media Management, SEO",
      technology: "AI",
      projects: "Marketing Campaign Analysis, Social Media Strategy",
      college: "University of XYZ",
      city: "Chicago",
      state: "Illinois",
    },
    {
      name: "Michael Brown",
      image: "https://cdn.pixabay.com/photo/2022/01/07/01/21/girl-6920625_1280.jpg",
      introduction: "I work as a software engineer at a leading tech company.",
      course: "Btech",
      status: "Professional",
      branch: "Software Engineering",
      skills: "C++, Java, Python, Machine Learning",
      technology: "ML",
      projects: "AI Chatbot, Data Analysis Tool",
      college: "Tech University",
      city: "Seattle",
      state: "Washington",
    },
    {
      name: "Sophia Lee",
      image: "https://cdn.pixabay.com/photo/2023/12/26/17/38/ai-generated-8470716_1280.png",
      introduction: "I am a student passionate about environmental science.",
      course: "Btech",
      status: "Student",
      branch: "Environmental Science",
      skills: "Data Analysis, Environmental Policy",
      technology: "Blockchain",
      projects: "Climate Change Research, Pollution Control Initiative",
      college: "Green University",
      city: "Portland",
      state: "Oregon",
    },
  ];

  module.exports = {data : sampleDetails};




